### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by bartoszmaka** [bartoszmaka/first-rails-app#2]
- [x] refactor specs
- [x] use simple_form forms
- [x] move view logic to decorators
- [x] move controller logic to service object
- [x] parsing #hashtags to tag links
- [x] Nested comments
- [ ] Article search by regex (ransack?)
- [x] gem brakeman
- [x] ~~simplify migrations~~
- [x] sort article comments by date / score
- [x] gem devise
- [x] Avatars
- [x] Improve css for mobile devices
- [x] Admins
- [x] Ban users
- [x] User roles
- [x] Allow users to upvote / downvote
- [x] Add publish date to article / comment view
- [x] Allow only owners to delete, edit their articles and comments
- [x] Require login to edit, delete, create
- [x] Css refactorization
- [x] User page reference in article/comment author field
- [x] Flash messages for create, delete, login, etc.
- [x] Migrate from SQLite to PostgreSQL
- [x] Migrations refactorization
- [x] shortcut for using comment.author instead of comment.article.user.name
- [x] User, Article, Comment relation
- [x] Change article and comment 'author' field to user reference
- [x] Login
- [x] Users
- [x] Articles search form
- [x] Tag.articles counter cache
- [x] 'Smart buttons' refactorization
- [x] Tags refactorization
- [x] Try to store page specific buttons somewhere, and generate them in smarter way
- [x] Add tags to article form
- [x] Add links to tags, that show all articles connected to tag
- [x] Tags create, update, delete
- [x] Tags validations (uniq, length)
- [x] RSpec
- [x] Tags
- [x] list error messages for wrongly created comment
- [x] bind comments to article, so deleting article will also delete article comments
- [x] implement comments update
